AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  redirection

  Sample SAM Template for redirection
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst


Resources:
  BasedRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/base-request/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 3
      Events:
        Api:
          Type: Api
          Properties:  
            Method: get
            Path: /request
      
        

  RedirectRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/redirect-request/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 28
      Events:
         Api:
          Type: Api
          Properties:  
            Method: get
            Path: /redirect
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "redirect"
  

      



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

